/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    Experience: typeof import('./components/Experience.vue')['default']
    ExperienceJob: typeof import('./components/ExperienceJob.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Social: typeof import('./components/Social.vue')['default']
  }
}
